---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: elastic_ubuntu
    image: docker.io/pycontribs/ubuntu:latest
    pre_build_image: true
    groups:
      - elasticsearch
    networks:
      - name: elk
#  - name: kibana_centos7
#    image: docker.io/pycontribs/centos:7
#    pre_build_image: true
#    groups:
#      - kibana
  - name: kibana_ubuntu
    image: docker.io/pycontribs/ubuntu:latest
    pre_build_image: true
    networks:
      - name: elk
    groups:
      - kibana
provisioner:
  name: ansible
  inventory:
    group_vars:
      kibana:
        default_elastic_host: elastic_ubuntu
verifier:
  name: ansible
#scenario:
#  test_sequence:
#    - destroy
#    - create
#    - converge
#    - verify
