---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: kibana
  gather_facts: false
  tasks:
  - name: Request to kibana
    command:
      cmd: curl http://localhost:5601/api/status
    register: result
  - name: Set a variable
    ansible.builtin.set_fact:
      response: "{{ result.stdout | from_json }}"
  - name: Version verify
    assert:
      that: response.version.number == "7.14.0"
